version: "3"

#Define Services
services:

  # Frontend Service 
  front_end:

    container_name: front_end_react
    
    build:
        context: ./cooking_steam_react
        dockerfile: Dockerfile
    
    stdin_open: true
    tty: true

    ports:
      - "3000:3000"
    volumes:
      - "/cooking_steam_react/app/node_modules"
      - "./cooking_steam_react:/app"
